name: update_ip
# 触发条件
on:
  workflow_dispatch:
  schedule:
   - cron: '30 20 * * *'
  #实际时间：+ 8小时  = 4:30
  #表达式生成  https://crontab.guru/
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #DDAL_EMAIL: ${{ secrets.DDAL_EMAIL }}
      #DDAL_PASSWORD: ${{ secrets.DDAL_PASSWORD }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Prepare #禁用了chrome
        run: pip install requests
      - name: 执行任务 -update IP
        run: |
          curl -o addressesapi.txt https://raw.githubusercontent.com/rxsweet/CM_Vmess/main/addressesapi.txt
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') update ip done"
          git pull --rebase
      - name: 推送更改
        uses:  ad-m/github-push-action@master
        with:
          branch: main
